### DISCUSSION TITLE
General Slowness?

### DISCUSSION THREAD

**Discussion by deathmock5** [happypandax/happypandax#273] [General]
So, When you have a large amount of galleries, what is the general cause of slowness when loading everything?
I'm sitting at only about 2k gallerys and the app is nearly unusable, as it takes 3-5 minutes to load a search.
Tried re-installing, reloading, same problems.
Tried setting up a sepperate reddis, postgres, and elasti servers for it, gave it 24 cores and 40gb of ram. put it on a cache drive of 15ssd in in a zpool and still it takes forever.
I mean, once the galleries are imported, they shouldent be this slow right? most of the relivent metadata and info should be cached right?

What can i do to speed it up?

Example Docker Compose with default creds and example mounts:
```
services:
  happypandax:
    image: twiddly/happypandax:latest
    ports:
      - "7006:7006"
      - "7007:7007"
      - "7008:7008"
    volumes:
      - /ssd2/data:/data
      - /hdd:/content
      - /ssd/downloads:/downloads
    links:
      - db
      - elasticsearch
      - redis
  db:
    image: postgres:latest
    ports:
      - 7005:5432
    environment:
      POSTGRES_USER: 'happypandax'
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - ./ssd2/db:/var/lib/postgresql/data
    logging:
      driver: none
  elasticsearch:
    image: elasticsearch:7.8.1
    ports:
      - 7010:9200
    environment:
      discovery.type: 'single-node'
      xpack.security.enabled: 'false'
      #ELASTIC_PASSWORD: 'happypandax'
      ES_JAVA_OPTS: '-Xmx2g -Xms2g'
    volumes:
      - /ssd2/es:/var/lib/elasticsearch/data
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '7009:6379'
    command: redis-server --save 60 1 --loglevel warning --requirepass happypandax
    volumes: 
      - /ssd2/redis:/data
 ```
