### ISSUE TITLE
Docker image is creating duplicate galleries upon restart

### ISSUE THREAD

**Issue by waz1500** [happypandax/happypandax#144]
**Describe the bug**
Docker HPX image create duplicate galleries on restart. Docker 0.11.0

**To Reproduce**
Steps to reproduce the behaviour:
1. Define /content and /data in docker image
2. Start up HPX
3. Galleries are automatically added. 
4. Restart HPX 
5. Galleries are duplicated again. 

**Expected behaviour**
Restarting HPX should not duplicate existing galleries previously added. I am using default config.yaml file in the docker image. 

```
import:
    skip_existing_galleries: true
    transparent_nested_folders: true
watch:
    enable: true
    dirs:
      - ${HPX_CONTENT}
    options:
      ${HPX_CONTENT}:
        import.scan_on_startup: true
```
