### ISSUE TITLE
Happypandax + Traefik (Reverse Proxy)

### ISSUE THREAD

**Issue by calgara12** [happypandax/happypandax#162]
**Describe the bug**
I just installed HappyPandaX with docker-compose. When i visit happypandax through my local ip address it works.

When i try to access it through my reverse proxy with happypandax.mydomain.com I get presented with a loading screen that never seems to finish loading.

**To Reproduce**
This is my docker-compose file:

```
version: '3.7'

services:
  happypandax:
    image: twiddly/happypandax:latest
    ports:
      - "4000:7006"
      - "4001:7007"
      - "4002:7008"
    networks:
      - happypandax_private
      - public
    volumes:
      - happypandax_config:/data
      - /mnt/manga:/content
    configs:
      - source: happypandax_config
        target: /data/config.yaml
    deploy:
      placement:
        constraints:
          - node.hostname == hostname
      labels:
        - traefik.frontend.rule=Host:manga.mydomain.com
        - traefik.enable=true
        - traefik.port=7008
        - traefik.tags=public
        - traefik.docker.network=public
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        - traefik.webservice.frontend.entryPoints=https

  db:
    image: postgres:latest
    restart: always
    ports:
      - 4003:5432
    environment:
      POSTGRES_USER: 'happypandax'
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - happypandax_db:/var/lib/postgresql/data
    logging:
      driver: none
    networks:
      - happypandax_private
    deploy:
      placement:
        constraints:
          - node.hostname == hostname

volumes:
  happypandax_db:
    driver: local
  happypandax_config:
    driver: local


networks:
  public:
    external: true
  happypandax_private:
    driver: overlay

configs:
  happypandax_config:
    file: ./config.yaml
```

And my config.yaml
```
import:                                  
    skip_existing_galleries: true        
    transparent_nested_folders: true     
watch:                                   
    enable: true                         
    dirs:                                
      - ${HPX_CONTENT}                   
    options:                             
      ${HPX_CONTENT}:                    
        import.scan_on_startup: true     
                                         
db:                                      
    dialect: postgres                    
    username: happypandax                
    password: postgres                   
    host: db                             
    port: 5432                           
    name: happypanda                     
```
**Expected behavior**
See the same thing on happypandax.mydomain.com as i see on 192.168.0.100:4002

**Logs**
```
TERM environment variable not set.


Starting HappyPanda X


HPX_DATA was defined, data will now be at: /data 


HPX_DATA was defined, data will now be at: /data 


Using postgres database 


Checking for database update 


Waiting on redis for maximum 20 seconds... 


Starting webserver... (0.0.0.0:7008) 
```

**Screenshots**
https://imgur.com/a/SBeR5vG

**Environment:**
 - OS: Ubuntu
 - Brave Version 0.68.142 Chromium: 77.0.3865.90 (Official Build) (64-bit)
 - HPX Version latest docker image

**Comment by twiddli** [comment]
Hello, having not used traefik before, I could only guess why it doesn't work.
In the NGINX example, [as shown in the docs](https://happypandax.github.io/usage.html#reverse-proxy), a path for the websocket endpoint had to be defined:
```
    # for websocket
    location /websocket {
        proxy_pass http://localhost:7008/websocket;
        proxy_redirect off;
        proxy_buffering off;
```

I imagine it's the same with traefik?
I'm not familiar with its configuration.

**Comment by calgara12** [comment]
Yeah that is probably it. 

so i just add this part to my config.yaml?

**Comment by twiddli** [comment]
No, it was meant as an example taken from the nginx configuration.
I think you'd have to look up the traefik-equivalent way of doing it.

**Comment by calgara12** [comment]
Hmm i don't think that i have to make any configuration in my traefik setup. usually when i add a new service i just add the labels to the docker service and it works just fine.
```
      labels:
        - traefik.frontend.rule=Host:manga.mydomain.com
        - traefik.enable=true
        - traefik.port=7008
        - traefik.tags=public
        - traefik.docker.network=public
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        - traefik.webservice.frontend.entryPoints=https
```

I fell like i have to change a setting on the happypandax site for it to work.
Do you have any idea what settings i might have to set for it to work? 

The site is reachable under manga.mydomain.com but something in the happypandax application doesnt stop loading.

Not sure how i can fix this. Thanks for helping me, i really appreciate it.

**Comment by twiddli** [comment]
I've tried setting it up using docker compose but I can't even get it to the loading screen at all?
I followed the quick start guide on their page:
```
version: '3'

services:
  happypandax:
    image: twiddly/happypandax:latest
    ports:
      - "7007:7007"
      - "7008:7008"
    labels:
      - traefik.http.routers.happypandax.rule=Host(`hpx.docker.localhost`)
      - traefik.port=7008

  proxy:
    image: traefik:v2.0
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
```
and I get:
```
$ curl -H Host:hpx.docker.localhost http://127.0.0.1
Bad Gateway
```

How were you able to get to the loading page?

**Comment by calgara12** [comment]
Hey, thanks for working this through with me.

Here is my traefik docker-compose:

```
version: '3.7'
services:
  traefik:
    image: traefik:1.7.13
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    command: >
      --api
      --acme
      --acme.storage=/certs/acme.json
      --acme.entryPoint=https
      --acme.httpChallenge.entryPoint=http
      --acme.onHostRule=true
      --acme.onDemand=false
      --acme.acmelogging=true
      --acme.email=my.mail@domain.com
      --docker
      --docker.swarmMode
      --docker.domain=mydomain.com
      --docker.watch
      --defaultentrypoints=http,https
      --entrypoints='Name:http Address::80'
      --entrypoints='Name:https Address::443 TLS'
      --logLevel=INFO
      --accessLog
      --metrics
      --metrics.prometheus
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik_certs:/certs
    configs:
      - source: traefik_htpasswd
        target: /etc/htpasswd
    networks:
      - public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.docker.network=public"
        - "traefik.port=8080"
        - "traefik.backend=traefik"
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:traefik.mydomain.com"
        - "traefik.frontend.auth.basic.usersFile=/etc/htpasswd"
        - "traefik.frontend.headers.SSLRedirect=true"
        - "traefik.frontend.entryPoints=http,https"

configs:
  traefik_htpasswd:
    file: ./htpasswd

networks:
  public:
    driver: overlay
    name: public

volumes:
  traefik_certs: {}
```

**Comment by twiddli** [comment]
Okay so after further reading on traefik, I got it working with this config:
```
version: '3.5'

services:
  hpx:
    image: twiddly/happypandax:latest
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:hpx.local
      - traefik.port=7008
      - traefik.frontend.entryPoints=http
      - traefik.docker.network=internal-network

    networks:
      internal-network:
        # the aliases are not required, but are useful if the applications want to internally
        # reference each other by host name
        aliases:
        - "hpx.local"

  proxy:
    image: traefik:1.7
    command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
    depends_on:
      - hpx
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    labels:
      - traefik.enable=true
      - traefik.port=8080
      - traefik.backend=traefik
      - traefik.docker.network=internal-network
    networks:
      - internal-network

networks:
  internal-network:
```

But with this, (without any modification from HPX), everything seems to work as expected and I'm getting past the loading screen?

**Comment by twiddli** [comment]
Okay, so after wanting to start using traefik myself since I really like the config discovery feature, I tried a more slightly complicated setup than above where traefik runs inside docker and connects to HPX running outside of docker.
I then started encountering the same issue and after having found out why, I find it very weird that the above setup worked.
Traefik's docs aren't the best, so after spending a couple of hours I finally got it to work.
In my case I set up traefik v2 instead of v1.7.
Here is my configuration:
`docker-compose.yaml`
```
version: '3.5'

services:
  traefik:
    image: traefik:v2.0.0
    ports:
      - "127.65.43.21:80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./dynamic-traefik.toml:/etc/traefik/dynamic-traefik.toml
    labels:
      - traefik.enable=true
      - traefik.port=8080
      - traefik.backend=traefik
      - traefik.docker.network=traefik-network
    networks:
      - traefik-network

networks:
  traefik-network:
    driver: bridge
```
`traefik.toml`
```
[global]
  checkNewVersion = true
  sendAnonymousUsage = true

[api]
  insecure = true

[providers]
  providersThrottleDuration = "2s"
  [providers.docker]
    exposedByDefault = false
    watch = true
    endpoint = "unix:///var/run/docker.sock"
    swarmModeRefreshSeconds = "15s"
  [providers.file]
    watch = true
    filename = "/etc/traefik/dynamic-traefik.toml"

[log]
  level = "DEBUG"
```
`dynamic-traefik.yaml`
```
[entryPoints]
  [entryPoints.http]
    address = ":80"

[http.routers]
  [http.routers.happypandax]
    entryPoints = ["http"]
    rule = "Host(`happypandax.local`)"
    service = "hpx-service"

[tcp.routers]
  [tcp.routers.happypandax]
    rule = "HostSNI(`*`)"
    service = "hpx-service"

[http.services]

  [http.services.hpx-service]
      [http.services.hpx-service.loadBalancer]
        [http.services.hpx-service.loadBalancer.sticky.cookie]
        [[http.services.hpx-service.loadBalancer.servers]]
          url = "http://host.docker.internal:7016"

[tcp.services]
  [tcp.services.hpx-service.loadBalancer]
    [[tcp.services.hpx-service.loadBalancer.servers]]
      address = "host.docker.internal:7016"
```

There are some extraneous settings, but the main take-away is that in addition to the `http` router (which obviously handles all the http requests), a `tcp` router also had to be defined to handle the websockets requests over the `ws` protocol.
Now, you're using v1.7 and the change between that and v2 are pretty drastic so I'm not sure if you want to upgrade + you're using a more complicated setup. I took a look at the docs for v1.7 to see if I could find an equivalent method but no luck. The docs aren't to helpful.

But this hopefully shows that the issue isn't with HPX.
If you have any questions, feel free to ask.
