### ISSUE TITLE
Docker-compose start up failure

### ISSUE THREAD

**Issue by Boycottangent** [happypandax/happypandax#218]
**Describe the issue**
Docker-compose installation and using rclone to mount onedrive directory as `content` file path. `docker-compose  -up` met
```
PermissionError: [Errno 13] Permission denied: '/data/data'
``` 
**Full logs here**
```
happypandax_1  | [7] Failed to execute script run
happypandax_1  | Traceback (most recent call last):
happypandax_1  |   File "run.py", line 7, in <module>
happypandax_1  |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
happypandax_1  |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
happypandax_1  |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
happypandax_1  |   File "/home/travis/virtualenv/python3.7.9/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
happypandax_1  |   File "happypanda/main.py", line 25, in <module>
happypandax_1  |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
happypandax_1  |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
happypandax_1  |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
happypandax_1  |   File "/home/travis/virtualenv/python3.7.9/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
happypandax_1  |   File "happypanda/common/clsutils.py", line 704, in <module>
happypandax_1  |   File "happypanda/common/clsutils.py", line 697, in setup_internal_db
happypandax_1  |   File "happypanda/common/clsutils.py", line 629, in __init__
happypandax_1  |   File "os.py", line 223, in makedirs
happypandax_1  | PermissionError: [Errno 13] Permission denied: '/data/data'
happypandax_happypandax_1 exited with code 255
```

**Here is my docker-compose.yml**
```yaml
version: '3'

services:
  happypandax:
    image: twiddly/happypandax:latest
    # start this container automatically on boot
    restart: always
    ports:
      - "7006:7006"
      - "7007:7007"
      - "7008:7008"
    volumes:
      - ./data:/data
      - /home/onedrive:/content
    links:
      - db

  db:
    image: postgres:latest
    restart: always
    ports:
      - 7005:5432
    environment:
      POSTGRES_USER: 'happypandax'
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - database:/var/lib/postgresql/data
    logging:
      driver: none
```
Is there any problem? Does HPX support reading web drive directory mounting by tools like rclone?

**Environment:**
 - OS: CentOS 7
 - HPX Version: latest (0.13.3)

**Comment by twiddli** [comment]
Hello, first, can you try replacing
``` 
      - ./data:/data
```
with
``` 
      - ./data:/data:z
```
and see if that works? Please don't do the same for the other volume yet.

I think a safer fix would be to replicate the `happypandax` user on your system too, and then allowing it to r/w the `./data` folder before mounting.
```
happypandax@f438253ecd74:/happypandax$ id happypandax
uid=101(happypandax) gid=101(happypandax) groups=101(happypandax)```

**Comment by twiddli** [comment]
I don't see why it wouldn't work if your `config.yaml` contains:
```
db:
    dialect: postgres
    username: happypandax
    password: postgres
    host: db
    port: 5432
    name: happypanda
```
