### ISSUE TITLE
Docker does not have config.yaml exposed to a easily editable location

### ISSUE THREAD

**Issue by ChronoStriker1** [happypandax/happypandax#231]
The config.yaml is located in a place that is unaccessable outside of the container and no way to edit from within the container.  Please move the file so its in the /data folder

**Comment by glop102** [comment]
What do you mean? It seems to work fine with where i was told to put it in the docs.
I was following https://happypandax.github.io/install.html#using-with-docker-compose

```
docker/happypandax# ls ./data/config.yaml 
./data/config.yaml
```
```
version: '3'
services:
  hpx:
    image: twiddly/happypandax:latest
    volumes:
      - ./data/:/data/
      - ./content/:/content/
```
