### ISSUE TITLE
[8] Failed to execute script run

### ISSUE THREAD

**Issue by symmetricalbyte** [happypandax/happypandax#264]
Starting happypandax with cli (non docker version).
And i get this error-
```
root@ubuntu-01:~# ./happypandax
Running HPX version 0.13.3

,--.  ,--.                                    ,------.                       ,--.            ,--.   ,--.
|  '--'  |  ,--,--.  ,---.   ,---.  ,--. ,--. |  .--. '  ,--,--. ,--,--,   ,-|  |  ,--,--.    \  `.'  /
|  .--.  | ' ,-.  | | .-. | | .-. |  \  '  /  |  '--' | ' ,-.  | |      \ ' .-. | ' ,-.  |     .'    \
|  |  |  | \ '-'  | | '-' ' | '-' '   \   '   |  | --'  \ '-'  | |  ||  | \ `-' | \ '-'  |    /  .'.  \
`--'  `--'  `--`--' |  |-'  |  |-'  .-'  /    `--'       `--`--' `--''--'  `---'   `--`--'   '--'   '--'
                    `--'    `--'    `---'
        ... . -. .- ? .- .-.. -... . -.. --- ? -.-- .- -.- ..- -- ---

Running HPX version 0.13.3
Using sqlite database

Traceback (most recent call last):
  File "run.py", line 15, in <module>
  File "happypanda/main.py", line 355, in start
  File "happypanda/common/hlogger.py", line 414, in init_listener
  File "multiprocessing/context.py", line 56, in Manager
  File "multiprocessing/managers.py", line 567, in start
  File "multiprocessing/connection.py", line 250, in recv
  File "multiprocessing/connection.py", line 407, in _recv_bytes
  File "multiprocessing/connection.py", line 383, in _recv
EOFError
[14836] Failed to execute script run
Sentry is attempting to send 0 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
```

When i use docker one it also shows the same thing.

**Comment by diamondsw** [comment]
Same thing. So... this project has been dead for over a year? Moving on...

**Comment by twiddli** [comment]
Try the newest version.

**Comment by diamondsw** [comment]
I'll recreate my environment and check; when I saw I was running into an issue almost a year old with no updates, I figured the project was dormant and deleted my compose.

**Comment by diamondsw** [comment]
No real change.

```
happypanda    | TERM environment variable not set.
happypanda    | [8] Failed to execute script run
happypanda    | Traceback (most recent call last):
happypanda    |   File "run.py", line 7, in <module>
happypanda    |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
happypanda    |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
happypanda    |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
happypanda    |   File "/home/travis/virtualenv/python3.7.9/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
happypanda    |   File "happypanda/main.py", line 25, in <module>
happypanda    |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
happypanda    |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
happypanda    |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
happypanda    |   File "/home/travis/virtualenv/python3.7.9/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
happypanda    |   File "happypanda/common/clsutils.py", line 704, in <module>
happypanda    |   File "happypanda/common/clsutils.py", line 697, in setup_internal_db
happypanda    |   File "happypanda/common/clsutils.py", line 629, in __init__
happypanda    |   File "os.py", line 223, in makedirs
happypanda    | PermissionError: [Errno 13] Permission denied: '/data/data'
```

There does not seem to be any concept of dealing with host permission mapping. The fact that it's trying to do something with "/data/data" indicates a logic error of some kind. Also, given that the fundamental error is failing to execute a script, this sounds like a container build issue more than anything.

I made some changes to the setup:

- I didn't see the point in using a bunch of host environment variables when this should exist in its own containerized environment. If these are required rather than a convenience (documentation is unclear), then that could be the issue.
- I also removed the "links" declaration and postgres port assignment as neither are needed for the happypandax container to talk to the database.
- I moved the postgres data to a bind mount so I can see what's going on if needed.
- I've already dealt with the [known permission issues with postgres](https://stackoverflow.com/questions/56188573/permission-issue-with-postgresql-in-docker-container) and gotten it running and set with the proper uid/gid (starting it separately has no errors, and its folder is populated as expected).

This is based on my experience with other containers, but let me know if there is something unique here where this would cause problems.

directory contents:
```
happypanda $ ls *
docker-compose.yml

content:
./  ../

data:
./  ../  config.yaml

db:
./   base/    pg_commit_ts/  pg_hba.conf    pg_logical/    pg_notify/	 pg_serial/	pg_stat/      pg_subtrans/  pg_twophase/  pg_wal/   postgresql.auto.conf  postmaster.opts
../  global/  pg_dynshmem/   pg_ident.conf  pg_multixact/  pg_replslot/  pg_snapshots/	pg_stat_tmp/  pg_tblspc/    PG_VERSION	  pg_xact/  postgresql.conf	  postmaster.pid
```

docker-compose.yml
```
version: '3'

services:
  happypanda:
    image: twiddly/happypandax:latest
    container_name: happypanda
    restart: unless-stopped
    ports:
      - "7006:7006" # Torrent port
      - "7007:7007" # Client port
      - "7008:7008" # Web UI port
    volumes:
      - ./data:/data
      - ./content:/content
  db:
    image: postgres:latest
    container_name: happypanda-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: 'happypandax'
      POSTGRES_PASSWORD: 'postgres'
    user: 1000:1000
    volumes:
      - ./db:/var/lib/postgresql/data
    logging:
      driver: none
```

config.yaml
```
import:
    skip_existing_galleries: true
    transparent_nested_folders: true
watch:
    enable: true
    dirs:
      - /content
    options:
      /content:
        import.scan_on_startup: true
plugin:
    plugin_dir: /data/plugins

db:
    dialect: postgres
    username: happypandax
    password: postgres
    host: db
    port: 5432
    name: happypanda
```
