### ISSUE TITLE
[Bug]: HPX Setup on Truenas w/ Docker

### ISSUE THREAD

**Issue by fapoverflow** [happypandax/happypandax#274]
Hello,
I'm trying to setup hpx on Truenas Scale using jailmaker & dockage.
```
version: "3"
services:
  happypandax:
    image: twiddly/happypandax:latest
    restart: always
    ports:
      - 7006:7006
      - 7007:7007
      - 7008:7008
    volumes:
      - /mnt/data/hpx:/data
      - /media/files:/content
    networks:
      - happy-panda-net
    links:
      - db
  db:
    image: postgres:latest
    restart: always
    ports:
      - 7005:5432
    environment:
      POSTGRES_USER: happypandax
      POSTGRES_PASSWORD: postgres
    volumes:
      - /mnt/data/postgres:/var/lib/postgresql/data
    logging:
      driver: none
    networks:
      - happy-panda-net
networks:
  happy-panda-net: null
```
At first, I got this error.
```
PermissionError: [Errno 13] Permission denied: '/data/data'
happy-panda-happypandax-1 exited with code 255
```
I tried adding an user for hpx and set write priviledges and ownership on `/mnt/data/hpx` dataset, but it didn't work may be cause I didn't set the right userid. So I just ended up giving all permissions for testing, then I got this error.
```
happy-panda-happypandax-1  | Running HPX version 0.13.3 
happy-panda-happypandax-1  | Using postgresql database 
happy-panda-happypandax-1  | Starting up, please wait... 
happy-panda-happypandax-1  | Starting webserver... (0.0.0.0:7008) 
happy-panda-happypandax-1  | [8] Failed to execute script run
happy-panda-happypandax-1  | Loading plugins from path: /data/plugins 
happy-panda-happypandax-1  | Loading plugins from path: plugins 
happy-panda-happypandax-1  | Loading 8 plugins 
happy-panda-happypandax-1  | Permission denied
happy-panda-happypandax-1  | Traceback (most recent call last):
happy-panda-happypandax-1  |   File "run.py", line 15, in <module>
happy-panda-happypandax-1  |   File "happypanda/main.py", line 447, in start
happy-panda-happypandax-1  |   File "happypanda/core/command.py", line 769, in emit
happy-panda-happypandax-1  |   File "happypanda/main.py", line 436, in <lambda>
happy-panda-happypandax-1  |   File "happypanda/main.py", line 207, in init_commands
happy-panda-happypandax-1  |   File "happypanda/core/command.py", line 329, in run
happy-panda-happypandax-1  |   File "happypanda/core/command.py", line 105, in _run
happy-panda-happypandax-1  |   File "happypanda/core/command.py", line 357, in _main_wrap
happy-panda-happypandax-1  |   File "happypanda/core/commands/item_cmd.py", line 592, in main
happy-panda-happypandax-1  |   File "happypanda/core/command.py", line 329, in run
happy-panda-happypandax-1  |   File "happypanda/core/command.py", line 105, in _run
happy-panda-happypandax-1  |   File "happypanda/core/command.py", line 357, in _main_wrap
happy-panda-happypandax-1  |   File "happypanda/core/commands/io_cmd.py", line 2246, in main
happy-panda-happypandax-1  |   File "happypanda/core/fswatch.py", line 200, in start
happy-panda-happypandax-1  |   File "watchdog/observers/api.py", line 255, in start
happy-panda-happypandax-1  |   File "watchdog/utils/__init__.py", line 110, in start
happy-panda-happypandax-1  |   File "watchdog/observers/inotify.py", line 121, in on_thread_start
happy-panda-happypandax-1  |   File "watchdog/observers/inotify_buffer.py", line 35, in __init__
happy-panda-happypandax-1  |   File "watchdog/observers/inotify_c.py", line 199, in __init__
happy-panda-happypandax-1  |   File "watchdog/observers/inotify_c.py", line 380, in _add_dir_watch
happy-panda-happypandax-1  |   File "watchdog/observers/inotify_c.py", line 401, in _add_watch
happy-panda-happypandax-1  |   File "watchdog/observers/inotify_c.py", line 417, in _raise_error
happy-panda-happypandax-1  | OSError: Permission denied
happy-panda-happypandax-1  | Sentry is attempting to send 0 pending error messages
happy-panda-happypandax-1  | Waiting up to 2 seconds
happy-panda-happypandax-1  | Press Ctrl-C to quit
happy-panda-happypandax-1 exited with code 0
```
I checked #243 & #254, but this looks different and there is nothing in `error.log`. Also, I found 2 new alpha images from last year on [dockerhub](https://hub.docker.com/r/twiddly/happypandax/tags). Are they addressing this issue ?

### HPX Version

latest

### OS

TrueNAS-SCALE-22

### Relevant HPX log output (`activity.log`, `error.log` or `debug.log`)

```shell
Jul-07 17:07:37--INFO   happypanda.main: HPX_DATA was defined, data will now be at: /data 
Jul-07 17:07:37--INFO   happypanda.main: HPX START 
Jul-07 17:07:37--INFO   happypanda.main: Running HPX version 0.13.3 
Jul-07 17:07:37--INFO   happypanda.main: DB Version: 0.9.0 
Jul-07 17:07:37--INFO   happypanda.main: Web Version: 0.13.1 
Jul-07 17:07:37--INFO   happypanda.main: Using python: 3.7.9 (default, Aug 23 2020, 05:33:53) 
[GCC 5.4.0 20160609] 
Jul-07 17:07:37--INFO   happypanda.main: ('x86_64', 'Linux-6.1.74-production+truenas-x86_64-with-debian-buster-sid') 
Jul-07 17:07:37--INFO   happypanda.migrate: Applying migrations 
Jul-07 17:07:37--INFO   [database].happypanda.core.db: Using postgresql database 
Jul-07 17:07:37--INFO   alembic.runtime.migration: Context impl PostgresqlImpl.
Jul-07 17:07:37--INFO   alembic.runtime.migration: Will assume transactional DDL.
Jul-07 17:07:37--INFO   [database].alembic.env: Migrating database main
Jul-07 17:07:37--INFO   alembic.runtime.migration: Context impl PostgresqlImpl.
Jul-07 17:07:37--INFO   alembic.runtime.migration: Will assume transactional DDL.
Jul-07 17:07:39--INFO   happypanda.main: Starting up, please wait... 
Jul-07 17:07:39--INFO   happypanda.main: Initiating background CheckUpdate 
Jul-07 17:07:39--INFO   happypanda.main: Initiating background auto BackupApplication 
Jul-07 17:07:39--INFO   happypanda.main: Initiating background TrashSweeper 
Jul-07 17:07:39--INFO   happypanda.main: Initiating background CacheCleaner 
Jul-07 17:07:39--INFO   happypanda.main: Initiating background download CacheCleaner 
Jul-07 17:07:39--INFO   happypanda.main: Initiating background thumbnail CacheCleaner 
Jul-07 17:07:39--INFO   happypanda.main: Initiating background pages CacheCleaner 
Jul-07 17:07:39--INFO   happypanda.main: Initiating background temp CacheCleaner 
Jul-07 17:07:39--INFO   happypanda.main: Initiating filters updater UpdateFilters 
Jul-07 17:07:39--INFO   [server].happypanda.core.fairy: Configuring redis server connection 127.0.0.1:7009:0 with password(False) 
Jul-07 17:07:39--INFO   [server].happypanda.core.fairy: Starting builtin redis server... 
Jul-07 17:07:39--INFO   [server].happypanda.core.fairy: Waiting on redis for maximum 20 seconds... 
Jul-07 17:07:40--INFO   [server].happypanda.core.esearch: Configuring elasticsearch server connection 127.0.0.1:7010 
Jul-07 17:07:40--INFO   [server].happypanda.core.esearch: Starting builtin ESearch server... 
Jul-07 17:07:40--INFO   [server].happypanda.core.esearch: Waiting on ESearch for maximum 60 seconds... 
Jul-07 17:07:48--INFO   [esearch].happypanda.core.db_esearch: Setting up database autoindexing 
Jul-07 17:07:48--INFO   happypanda.main: Starting webserver... (0.0.0.0:7008) 
Jul-07 17:07:48--INFO   [plugin].happypanda.core.plugins: Loading plugins from path: /data/plugins 
Jul-07 17:07:48--INFO   [plugin].happypanda.core.plugins: Loading plugins from path: plugins 
Jul-07 17:07:48--INFO   [plugin].happypanda.core.plugins: Loading 8 plugins 
Jul-07 17:07:48--INFO   happypanda.main: Initiating default item watcher, watching 1 folders 
Jul-07 17:07:48--INFO   [command].happypanda.core.commands.item_cmd: Watching the following folders for new items: set([CoreFS(/content)])
```

### Did you check for similar issues?

- [X] I checked and didn't find similar issues.

**Comment by fapoverflow** [comment]
After some digging, I was able to run hpx but I still faces some issues.
The permissions issues was actually the same as #243 and I ended up building my own image. The esearch service couldn't run as root, so the image must include a specific user for hpx.
I was able to restore my hp database by using the windows gui to migrate, then editing the backup with an sqlite client and exporting it into the container and scanning.
```
UPDATE "happypanda.backup".page SET path = replace( path, 'C:\path\to\Files\', '/content/');
UPDATE "happypanda.backup".page SET path = replace( path, '\', '/');
```

Using only 1 volume to store the config & data was confusing because of some weird nested folder behavoir, so I end up using 2, plus a 3rd one specific for the config.yaml file.
```
version: "3"
services:
  happypandax:
    image: faptain/happypandax:0.13.3
    restart: always
    ports:
      - 7006:7006
      - 7007:7007
      - 7008:7008
    volumes:
      - /mnt/data/hp/data:/data
      - /mnt/data/hp/config:/happypandax/data
      - /mnt/data/hp/config/config.yaml:/happypandax/config.yaml
      - /media/Files:/content
```

Imported favorites are linked to the default user. Is there a way to link them to another ? or maybe rename default user ?
I'm currently looking to migrate to postgresql for better performance, even if it's not supported for now. 
Also, I was never able to connect with hpx desktop client despite ports being exposed.

@twiddli Thank you a lot for your work.
It must have been a major commitment and I think it would be a shame if this project died.
Being inactive for a long time, maybe releasing the backend sources could revive it.
At least, it would help debbuging and building new docker images.

I made a [fork](https://github.com/fapoverflow/happypandax) if anyone need to build their own image, even if it still requires to download a release manually and set some variables.
